/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './screens/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#5ED5A8',
        'primary-2': '#5CD6A5',
        'primary-3': '#9AF2CB',
        'primary-4': '#DFFBED',
        'primary-5': '#BFF7DC',

        background: '#1B232A',
        'background-2': '#161C22',
        'background-3': '#1B1F27',
        'background-secondary': '#083D2B',
        'background-secondary-2': '#0D4F36',
        'background-secondary-3': '#126843',
        'background-tertiary': '#141820',
        secondary: '#777777',
        'secondary-2': '#29333D',
        tertiary: '#252E35',
        'tertiary-2': '#222830',
        'tertiary-3': '#546273',
        'custom-tertiary': '#23362F',
        foreground: '#171D22',
        'custom-text': '#C1C7CD',
        'custom-text-2': '#A7AFB7',
        'custom-text-3': '#080C11',
        'custom-text-secondary': '#F1F6F8',
        'custom-text-tertiary': '#8594A6',
        extra: '#E3E8ED',
        'custom-extra': '#F1F6F8',
        destructive: '#DD4B4B',
        'destructive-2': '#E4484C',
        'destructive-3': '#E45252',
        notify: '#4AA8FF',
        warning: '#D5BB5E',
        'warning-2': '#2B2416',
        'warning-3': '#C9A96C',
        'warning-4': '#DB9E38',
      },
      fontFamily: {
        'nm-light': ['NeueMontreal-Light'],
        nm: ['NeueMontreal'],
        'nm-medium': ['NeueMontreal-Medium'],
        'nm-bold': ['NeueMontreal-Bold'],
      },
    },
  },
  plugins: [],
};
