export const NOTIFICATION_DATA = [
  {
    id: 1,
    type: 'withdrawal',
    title: 'Withdrawal Successful',
    message: 'You have successfully withdrawed lorem ipsum dolor sit...',
    read: false,
    status: 'success',
  },
  {
    id: 2,
    type: 'deposit',
    title: 'Deposit Successful',
    message: 'You have successfully deposited lorem ipsum dolor sit...',
    read: false,
    status: 'warning',
  },
  {
    id: 3,
    type: 'security',
    title: 'Login From An Unknown Device',
    message: 'Your account was logged from an unknown device lorem...',
    read: false,
    status: 'urgent',
  },
  {
    id: 4,
    type: 'withdrawal',
    title: 'Withdrawal Successful',
    message: 'You have successfully withdrawed lorem ipsum dolor sit...',
    read: false,
    status: 'success',
  },
  {
    id: 5,
    type: 'withdrawal',
    title: 'Withdrawal Successful',
    message: 'You have successfully withdrawed lorem ipsum dolor sit...',
    read: false,
    status: 'success',
  },
  {
    id: 6,
    type: 'withdrawal',
    title: 'Withdrawal Successful',
    message: 'You have successfully withdrawed lorem ipsum dolor sit...',
    read: false,
    status: 'success',
  },
  {
    id: 7,
    type: 'withdrawal',
    title: 'Withdrawal Successful',
    message: 'You have successfully withdrawed lorem ipsum dolor sit...',
    read: false,
    status: 'success',
  },
  {
    id: 8,
    type: 'withdrawal',
    title: 'Withdrawal Successful',
    message: 'You have successfully withdrawed lorem ipsum dolor sit...',
    read: false,
    status: 'success',
  },
  {
    id: 9,
    type: 'withdrawal',
    title: 'Withdrawal Successful',
    message: 'You have successfully withdrawed lorem ipsum dolor sit...',
    read: false,
    status: 'warning',
  },
  {
    id: 10,
    type: 'withdrawal',
    title: 'Withdrawal Successful',
    message: 'You have successfully withdrawed lorem ipsum dolor sit...',
    read: false,
    status: 'urgent',
  },
] as const;
